invex/config/routes.rb
Rails.application.routes.draw do
  resources :scenes
  resources :chapters
  resources :scripts
  resources :histories
  # devise_for :users

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'histories#index'

  get 'scenes_cont', to: 'scenes#cont'
  post 'scenes_cont', to: 'scenes#cont'

  get 'scene3', to: 'scenes#scene3'

  get 'scene4', to: 'scenes#scene4'

  get 'congratulation', to: 'scenes#congratulation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

invex/app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :history
  has_many :falas
end

invex/app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]
  before_action :set_history, only: [:show, :cont]

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
    # raise("houahauohauo")
    @scene = Scene.all.where("history_id = #{params[:id]}")

  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render :show, status: :created, location: @scene }
      else
        format.html { render :new }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { render :show, status: :ok, location: @scene }
      else
        format.html { render :edit }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url, notice: 'Scene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cont
    @scene = Scene.find(2)
  end

  def scene3
    @scene = Scene.find(3)
  end

  def scene4
    @scene = Scene.find(4)
  end

  def congratulation
    respond_to do |format|
      format.html { render 'congratulation'}
      format.json { head :no_content }
    end
    # flash[:success] = "Com o galho, você volta para a sala de pesquisa, recupera a chave, e vai para sua casa."
    # redirect_to 'congratulation'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

  def set_history
    @history = History.all
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:imagem, :history_id)
    end
end

invex/app/helpers/scenes_helper.rb
module ScenesHelper
end

invex/app/views/scenes/_form.html.erb
<%= form_with(model: scene, local: true) do |form| %>
  <% if scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% scene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :imagem, 'Caminho da imagem' %>
    <%= form.text_field :imagem %>
  </div>


  <div class="field">
    <%= form.label :history_id %>
    <%#= form.text_field :history_id %>
    <%= form.select :history_id, History.all.collect{|p| [ p.titulo, p.id ] }, { include_blank: "Selecione" } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

invex/app/views/scenes/congratulation.html.erb
<!-- Style do background -->
<style>
  body{
    background: #1a1026;
  }

</style>

<div class="container-fluid">

  <div class="card mb-3 text-center" style="max-width: 630px; max-height: 630px; margin-left: 300px;">
    <%= image_tag 'congratulation.jpg', class: 'card-img'%>
    <div class="card-img-overlay">
      <h1 class="card-title text-dark" style="font-size: large">Parabéns!!</h1>
      <p class="card-text text-danger" style="font-size: large">Com o galho, você volta para a sala de pesquisa, recupera a chave, e vai para sua casa.</p>
    </div>
  </div>



</div>

<!--    <div class="btn">-->
<%#= link_to 'Ir até sua sala de pesquisa, checar se deixou a chave lá.' , scene_path(id: 3), class: "text-primary" %>
<!--    </div>-->

invex/app/views/scenes/cont.html.erb
<!-- Style do background -->
<style>
  body{
    background: #1a1026;
  }

</style>

<div class="container-fluid">
  <div class="card mb-3" style="max-width: 100%;">
    <div class="row no-gutters">
      <div class="col-md-5">
        <%= image_tag(@scene.imagem, class: "card-img-top", style: 'height: 550px;')%>
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <div class="row">
            <div class="col-sm-10" align="center" style="margin-left: 40px;">
              <div class="text-justify text-dark" style="text-align: center">
                <%= @scene.descricao %>
              </div>
            </div>
          </div>
        </div>
        <p> </p>
        <div class="col-sm-12" style="text-align: center">
          <p class="text-dark" style="font-size: medium">Com isso em mente, você decide:</p>
        </div>
        <div class="btn" style="margin-top: 50px; margin-left: 250px;">
          <%= link_to 'Ir até sua sala de pesquisa.' , scene3_path(id: 3), class: "text-primary" %>
        </div>
      </div>
    </div>
  </div>
<!--  <div class="card ">-->
    <%#= image_tag(@scene.imagem, class: "card-img-top")%>
<!--    <div class="card-body">-->
<!--      <div class="text-justify text-dark" style="float: left;">-->
        <%#= @scene.descricao %>
<!--      </div>-->
<!--    </div>-->
<!--    <div class="col-sm-12" style="text-align: center">-->
<!--    <p class="text-dark" style="font-size: medium">Com isso em mente, você decide:</p>-->
<!--    </div>-->
<!--    <div class="btn">-->
    <%#= link_to 'Ir até sua sala de pesquisa, checar se deixou a chave lá.' , scene3_path(id: 3), class: "text-primary" %>
<!--    </div>-->
<!--  </div>-->
</div>

invex/app/views/scenes/edit.html.erb
<h1>Editing Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

invex/app/views/scenes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scenes</h1>

<table>
  <thead>
    <tr>
      <th>Imagem</th>
      <th>History</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.imagem %></td>
        <td><%= scene.history %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scene', new_scene_path %>

invex/app/views/scenes/new.html.erb
<h1>New Scene</h1>

<%= render 'form', scene: @scene %>

<%= link_to 'Back', scenes_path %>

invex/app/views/scenes/scene3.html.erb
<!-- Style do background -->
<style>
  body{
    background: #1a1026;
  }

</style>

<div class="container-fluid">



  <div class="card ">
    <%= image_tag(@scene.imagem, class: "card-img-top")%>
    <div class="card-body">
      <div class="text-justify text-dark" style="float: left;">
        <%= @scene.descricao %>
      </div>
    </div>

    <div class="accordion" id="accordionExample">
      <div class="card">
        <div class="card-header" id="headingOne">
          <button class="btn" style="color: #3C7FB0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Olhar por baixo da porta.
          </button>
        </div>

        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="row">
            <div class="card-body col-sm-7" style="color: blue">
              Você nota que a chave está ali no chão, atrás da porta, mas não consegue alcançá-la com o que tem.
            </div>
            <div class="col-sm-3" >
              <div style="float: right; margin-left: 30%; margin-top: 4%;">
                <%= link_to 'Voltar à entrada.' , scene4_path(4), class: "btn btn-primary text-dark" %>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="card">
        <div class="card-header" id="headingTwo">
          <h2 class="mb-0">
            <button class="btn " style="color: #3C7FB0" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Arrombar a porta!!!!
            </button>
          </h2>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
          <div class="card-body" style="color: blue">
            Você para e diz para si mesmo: “Sério mesmo? Patrimônio público? Quer se meter nisso mesmo?”, e se recusa a fazer isso.
          </div>
    </div>
      </div>
    </div>
  </div>
</div>

invex/app/views/scenes/scene4.html.erb
<!-- Style do background -->
<style>
  body{
    background: #1a1026;
  }

</style>

<div class="container-fluid">

  <div class="card ">
    <%= image_tag(@scene.imagem, class: "card-img-top")%>
    <div class="card-body">
      <div class="text-justify text-dark" style="float: left;">
        <%= @scene.descricao %>
      </div>
    </div>

    <p class="text-dark" style="font-size: medium; margin-left: 1em;"> Então você decide:  </p>

    <div class="accordion" id="accordionExample">
      <div class="card">
        <div class="card-header" id="headingOne">
          <button class="btn" style="color: #3C7FB0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Pegar uma folha seca.
          </button>
        </div>

        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body" style="color: blue">
            Você pega uma folha seca, mas percebe que ela pode quebrar ao manejar ela.
          </div>
        </div>

      </div>
      <div class="card">
        <div class="card-header" >
          <%= link_to 'Pegar um galho!', congratulation_path, class: "text-primary"%>
<!--            <button class="btn " style="color: #3C7FB0" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">-->
<!--              Arrombar a porta!!!!-->
<!--            </button>-->
        </div>

      </div>
    </div>
  </div>
</div>

<!--    <div class="btn">-->
<%#= link_to 'Ir até sua sala de pesquisa, checar se deixou a chave lá.' , scene_path(id: 3), class: "text-primary" %>
<!--    </div>-->

invex/app/views/scenes/show.html.erb
<!-- Style do background -->
<style>
  body{
    background: #1a1026;
  }

</style>
<div class="container-fluid">

  <div class="card mb-3" style="max-width: 100%;">
    <div class="row no-gutters">
      <div class="col-md-5">
        <%= image_tag(@scene[0].imagem, class: "card-img-top", style: 'height: 550px;')%>
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <h6 class="text-dark"><%= @scene[0].descricao%></h6>
        </div>
          <div class="accordion" id="accordionExample">-->
            <div class="card">
              <div class="card-header" id="headingOne">
                  <button class="btn" style="color: #cc0000" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                   - "Tem mais gente no bloco?"
                  </button>
              </div>

              <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body" style="color: blue">
                 - “Não, já foram todos pra casa.”
                </div>
              </div>
            </div>
            <div class="card">
              <div class="card-header" id="headingTwo">
                <h2 class="mb-0">
                  <button class="btn " style="color: #cc0000" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    - "O senhor pode me dizer se as salas estão abertas?"
                  </button>
                </h2>
              </div>
              <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body" style="color: blue">
                 - "Algumas, eu acho, mas não sei dizer quais."
                </div>
                <div class="row">
                  <div class="col-sm-12 text-dark" style="alignment: left; margin-left: 40px;">
                    Com isso em mente, você decide:
                  </div>
                </div>
                <br>
                <div class="fom-group">
                  <div class="row" style="margin-left: 20px;">
                    <div class="col col-sm-5 text-dark">
                      <%= link_to 'Decide ir ao banheiro', scenes_cont_path(2) ,class: "text-primary" %>
                    </div>
                    <div class="col col-sm-7 text-dark">
                      <%= link_to 'Ir até sua sala de pesquisa.', scene3_path(3),class: "text-primary" %>
                    </div>
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
</div>