invex/config/routes.rb
Rails.application.routes.draw do
  resources :scenes
  resources :chapters
  resources :scripts
  resources :histories
  # devise_for :users

  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'histories#index'

  get 'scenes_cont', to: 'scenes#cont'
  post 'scenes_cont', to: 'scenes#cont'

  get 'scene3', to: 'scenes#scene3'

  get 'scene4', to: 'scenes#scene4'

  get 'congratulation', to: 'scenes#congratulation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

invex/app/models/script.rb
class Script < ApplicationRecord
  belongs_to :user
  belongs_to :history
end

invex/app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:user_id, :history_id, :titulo)
    end
end

invex/app/helpers/scripts_helper.rb
module ScriptsHelper
end

invex/app/views/scripts/_form.html.erb
<%= form_with(model: script, local: true) do |form| %>
  <% if script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :history_id %>
    <%= form.text_field :history_id %>
  </div>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

invex/app/views/scripts/edit.html.erb
<h1>Editing Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

invex/app/views/scripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scripts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>History</th>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scripts.each do |script| %>
      <tr>
        <td><%= script.user %></td>
        <td><%= script.history %></td>
        <td><%= script.titulo %></td>
        <td><%= link_to 'Show', script %></td>
        <td><%= link_to 'Edit', edit_script_path(script) %></td>
        <td><%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Script', new_script_path %>

invex/app/views/scripts/new.html.erb
<h1>New Script</h1>

<%= render 'form', script: @script %>

<%= link_to 'Back', scripts_path %>

invex/app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @script.user %>
</p>

<p>
  <strong>History:</strong>
  <%= @script.history %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @script.titulo %>
</p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>